### ISSUE TITLE
Queue clean up cron job

### ISSUE THREAD

**Issue by liustanley** [sandboxnu/office-hours#110]
Clean up questions at the end of the queue, once every hour, or whenever someone checks out

@dajinchu not sure if this should be specified further

**Comment by willstenzel** [comment]
If there are questions left in the queue when its being "cleaned up" what should the status be set as? 

Right now our `ClosedQuestionStatus` has 
```
  Resolved = "Resolved",
  Deferred = "Deferred",
  NoShow = "NoShow",
  Deleted = "Deleted",
```

**Comment by dajinchu** [comment]
Good call yeah Stale is a great idea
