### ISSUE TITLE
Update question status types to distinguish who deleted the question

### ISSUE THREAD

**Issue by willstenzel** [sandboxnu/office-hours#190]
**Description:** 
Currently we when a question is deleted we mark it with the `ClosedQuestionStatus.Deleted`. However, this does not allow us to distinguish who deleted the question. 
 
In order to keep track of who deleted the Question we will probably want to split the `Deleted` status into `DeletedByStudent` and `DeletedByTA`.

**Specs:**
- [ ] Update the types to contain `DeletedByStudent` and `DeletedByTA`
- [ ] Hook up the "Remove from Queue" button on the TA side to use the `DeletedByTA` status
- [ ] Hook up the "Leave Queue" button on the Student side to use the `DeletedByStudent` status

Contact @willstenzel if blocked

**Comment by liustanley** [comment]
Did we decide that this isn't needed?

**Comment by willstenzel** [comment]
> Did we decide that this isn't needed?

Yeah I don't think we really need it
