### ISSUE TITLE
Handle leftover students in queue

### ISSUE THREAD

**Issue by liustanley** [sandboxnu/office-hours#197]
**Description:**
At the end of a scheduled queue, we need to add support for students who were unable to get help in time. Our desired flow is as follows:

1. Queue closes while student is still 'Queued'
2. Student's question is closed, but marked as 'Leftover'
3. Modal appears on student's screen describing that the queue has been closed, but they can join the next available queue via priority registration if they want to

**Specs:**
- [ ] Leftover questions are closed and marked as 'Leftover' when a queue closes
- [ ] Modal appears on student's screen describing that the queue has been closed, but they can join the next available queue via priority registration
- [ ] Answering 'yes' will find the next queue and add them, as well as send them a reminder before the queue starts
- [ ] Answering 'no' will change their question status to 'Deleted'

Contact @liustanley if blocked.

**Comment by NEUDitao** [comment]
I think we have the capabilities to do this now, especially since we have priority queue in.

**Comment by willstenzel** [comment]
I wonder how much value this would add in proportion to the amount of complexity. In my opinion, if it's not a feature that at least some of the users would be excited about, then it's probably not worth adding. Might be worth talking to some people to see how big of an issue "leftover" questions are.

**Comment by liustanley** [comment]
Yeah I think I agree with this. Maybe an easier alternative could be to export the emails of leftover students for staff to use however they decide?
