### ISSUE TITLE
Design professor analytics email

### ISSUE THREAD

**Issue by liustanley** [sandboxnu/office-hours#289]
Create mockups for a Weekly Digest for professors, summarizing what happened in Office Hours that week.

Don't format as an email, maybe send a PDF or a banner that you can click into to bring to a slideshow, etc.

**Core Insights**
Explain for each statistic what its purpose is/maybe incorporate the number into the sentence.

**Course Health:**

How many students in this course needed help this week?
- [ ] Number of unique students that came to Office Hours that week [Compare with previous week]

How much help was needed per day?
- [ ] Number of questions asked in Office Hours each day that week, day by day breakdown [Compare with previous week]

What students are struggling/attending office hours frequently?
- [ ] List of students with frequent repeats per week (eg, > 3x sessions/week)

How many students are struggling to understand the subject material?
- [ ] Number of (student-categorized) `Concept` questions were asked this week (as a percent) [Compare with previous week]

**Office Hour Efficiency:**

How efficient were office hours this week?
- [ ] Number of questions that were answered/not answered

What does office hour load look like throughout the week?
- [ ] Wait time calendar heat map as a PNG

https://medium.com/engagement-marketing-smiles/the-art-of-the-digest-email-25537c67fe93

**Comment by tsachleben** [comment]
Easy data that would be helpful to see:
- Number of students/day
- Number of students helped/TA/day
- Average time helping a single student/TA/week
- Students w/ frequent repeats/week (eg, > 3x sessions/week)

Harder data that would be astonishing to see:
- Keyword analysis on student questions (eg number of instances of "project 1")
- TA-keyword matrix (eg, Number of students helped by TA X for keyword Y)
- Average help time, broken down by keyword (eg. across all TAs, average help time for keyword Y)
