### ISSUE TITLE
Notify course instructors when queue grows to 4 people in length

### ISSUE THREAD

**Issue by liustanley** [sandboxnu/office-hours#300]
Notify via SMS, I'm not sure how to only notify course coordinators/professors. This might be something we have to coordinate with Khoury Admin?

Tariq: "So that I can get a note that I need to check-in w/ the TAs online and/or join queue myself."

**Comment by NEUDitao** [comment]
could maybe have it configurable in a settings page somewhere for the professor to enable thhis feature-- and then just do the check whenever a student creates a question
