### ISSUE TITLE
User Auth Management

### ISSUE THREAD

**Issue by dajinchu** [sandboxnu/office-hours#31]
- Set a cookie with user auth token
- API endpoints return 401 accordingly

https://hapi.dev/module/cookie/api/?v=11.0.1

This ticket does NOT involve working with Khoury to actually handle logging in. It just sets up everything _after_ the login succeeds.

**Comment by liustanley** [comment]
is this issue closed by #36 @dajinchu @willstenzel ?

**Comment by willstenzel** [comment]
Yep!
