### ISSUE TITLE
Fix Queue Card formatting when more than three TA's are checked in

### ISSUE THREAD

**Issue by willstenzel** [sandboxnu/office-hours#325]
We'll either need to add some padding on top of the buttons or stack them vertically when there is three TA's checked in. 

![image](https://user-images.githubusercontent.com/33739155/93400666-48c18100-f84e-11ea-826c-77780cfb534f.png)

**Comment by NEUDitao** [comment]
did we fix this?

**Comment by willstenzel** [comment]
> did we fix this?

No, this issue still exists. We might also want to wrap the names in the title of the card if it's easy.

![image](https://user-images.githubusercontent.com/33739155/107566858-5d166980-6bb3-11eb-919d-66644e29084b.png)
