### ISSUE TITLE
Redesign profile feature(s)

### ISSUE THREAD

**Issue by liustanley** [sandboxnu/office-hours#348]
**Description**
We have a profile button in the top right of our app, but it's very clunky and doesn't actually work all that well, both functionally and visually:

![Current profile flow](https://i.gyazo.com/3c3d1c452e6b84c65bd8011bbb73b32d.gif)

**Specs**
Here's a list of features we want to include in this new profile feature:
- [x] Web notifications toggle
- [x] Phone notifications toggle + input
- [x] Ability for user to change their preferred name
- [x] Ability for user to upload their own picture
- [x] Logout button

If blocked, contact @liustanley

**Comment by willstenzel** [comment]
Here's an option for the redesigned menu drop down

![image](https://user-images.githubusercontent.com/33739155/93962379-bc6cfd80-fd28-11ea-8292-f2c8d149dbf3.png)

**Comment by liustanley** [comment]
Separate settings page with two dividers for Profile Settings and Notification Settings.
Dropdown:
- Link to settings page
- External pages (Help Guide, Release Notes)
- Logout button (make this distinctly a logout action)
