### ISSUE TITLE
As course staff, I would like to ask a student in the queue to add more detail without removing them from the queue

### ISSUE THREAD

**Issue by dmelcer9** [sandboxnu/office-hours#386]
- [ ] Add an "Ask for question revision" button next to the "Help" button for a student
- [ ] Clicking this button opens a modal with a text input (initially "Could you give more detail on your question?"), and OK/Cancel buttons
- [ ] If OK is pressed, the student will receive a notification "You have been asked to revise your question", and a modal will show with the staff input and an "Edit question" button
- [x] If the student's status changed to being helped while the modal is displaying, dismiss the modal

Please note that asking a student to revise their question won't affect their question status, it will only send them a notification and display the modal.

**Comment by dfarooq610** [comment]
implemented with the "rephrase question" modal! #836
