### ISSUE TITLE
Allow queue notes to support links and possibly markdown

### ISSUE THREAD

**Issue by willstenzel** [sandboxnu/office-hours#398]
**Story Spec**
- [ ] Edit queue notes -> textarea
- [ ] New lines and links will display correctly in the queue notes

On multiple occasions I've seen TA's have added links in the queue notes. It would be nice to allow students to click directly on the live links instead of having them copy paste it. 

Supporting markdown would solve this issue but it would also mean that we might have to redesign the way that the queue notes are shown on the `OpenQueueCard`.

**Comment by NEUDitao** [comment]
still needs to be done.

**Comment by willstenzel** [comment]
Should we use something like react-linkify?

https://www.npmjs.com/package/react-linkify

**Comment by liustanley** [comment]
Yeah I've been waiting on this because I think we need a different queue layout to give queue notes more room, and I'd like to get question grouping / data insights done first.

**Comment by liustanley** [comment]
- [ ] Edit queue notes -> textarea
- [ ] New lines and links will display correctly in the queue notes
