### ISSUE TITLE
Prevent resizeObserver errors from showing on elasticAPM

### ISSUE THREAD

**Issue by willstenzel** [sandboxnu/office-hours#423]
@dajinchu mentioned that we should be able to write some frontend code to filter out the `resizeObserver` error

**Comment by dfarooq610** [comment]
@willstenzel is this still relevant? We dont use elasticAPM but this issue may transition to sentry somehow

**Comment by willstenzel** [comment]
If we are no longer using elasticAPM this should no longer be an issue.
