### ISSUE TITLE
Nest.js migration dev design

### ISSUE THREAD

**Issue by liustanley** [sandboxnu/office-hours#46]
hapi is kill so we have to migrate to www.nestjs.com

Plan for this story is to research the framework, do tutorials, and create a dev design for how we're going to accomplish the backend migration from hapi to nest.js. If we're able to finish this earlier than planned, we can just get started on implementation.

**Comment by liustanley** [comment]
we should look into making sure the stuff we were doing with `hapi/cookie` in #36  is still possible in nest.js

**Comment by dajinchu** [comment]
Feature     | Hapi Implementation | Nest Implementation
------------- | ---------------------------  | ----------------------------
DB/ORM  |     TypeORM              |     TypeORM
Auth         | hapi/cookie                | [passport `session: true` sets a cookie](https://docs.nestjs.com/techniques/authentication#customize-passport)
Validation |  hapi/joi                     |
Test Factories |  typeorm-factory | 
Dev Fixtures | typeorm-fixtures-cli |
Environment variables | dotenv/custom .env loader | https://docs.nestjs.com/techniques/configuration
Logging | hapi-dev-errors               | https://docs.nestjs.com/techniques/logger
Testing | `server.inject`              | https://docs.nestjs.com/fundamentals/testing#testing
