### ISSUE TITLE
Support instructor login

### ISSUE THREAD

**Issue by liustanley** [sandboxnu/office-hours#474]
- [ ] When a professor or course coordinator logs in to the app, their user course for the course they teach should be set to professor

@willstenzel can you drop the log in schema returned by Khoury Admin here?

**Comment by willstenzel** [comment]
```
{
   "email":"a.grob@northeastern.edu",
   "campus":116,
   "first_name":"Alexander",
   "last_name":"Grob",
   "photo_url":"https://prod-web.neu.edu/wasapp/EnterprisePhotoService/PhotoServlet?vid=CCS&er=d1d26b1327817a8d34ce75336e0334cb78f33e63cf907ea82da6d6abcfc15d66244bb291baec1799cf77970e4a519a1cf7d48edaddb97c01",
   "professor": 1,
   "courses":[
      {
         "crn":18513,
         "course":"CY 5210",
         "section":1,
         "semester":"202110",
         "title":"Information System Forensics",
         "campus":"Online"
      }
   ],
   "ta_courses":[
      {
         "course":"CS 2500",
         "semester":"202110"
      }
   ]
}
```

**Comment by liustanley** [comment]
wait @willstenzel how can you tell which course they're a professor for here?

**Comment by willstenzel** [comment]
> wait @willstenzel how can you tell which course they're a professor for here?

Sorry forgot to clarify, if the professor flag is `1` (meaning that they are a professor) the `ta_courses` array contains the list of classes that they are a professor for.

**Comment by NEUDitao** [comment]
@willstenzel are `courses` for a professor just student courses still then? (I doubt they'll exist but that's always a possibility right?)

**Comment by willstenzel** [comment]
> @willstenzel are `courses` for a professor just student courses still then? (I doubt they'll exist but that's always a possibility right?)
> 
> 

Yeah I think you're right. We'd have to ask Alex Grob to confirm though.
