### ISSUE TITLE
Modify login endpoint to only use enabled courses

### ISSUE THREAD

**Issue by liustanley** [sandboxnu/office-hours#507]
We'll only enable courses for the current semester, so the login endpoint should only consider these enabled courses when logging a user in.

**Comment by willstenzel** [comment]
I don't think we'll have to worry about enabled courses for the login endpoint. The `CourseSectionMappingModel` is used to determine what courses are going to be added for a user who logs in so as long as the course section mappings get updated before the semester starts we should be good.
