### ISSUE TITLE
Admin page

### ISSUE THREAD

**Issue by dajinchu** [sandboxnu/office-hours#53]
Simple page that lets admins:
- Enable office hours for a course
- input the ical URL

**Comment by willstenzel** [comment]
Once we get nest.js setup this could package could really help us out.
https://nestjs-admin.com/

**Comment by liustanley** [comment]
@dajinchu does our current admin page allow us to enable office hours for a course? or do we need to do more work on this

**Comment by dajinchu** [comment]
I believe once @willstenzel's login pr gets merged we will. He added `enabled` to the course model

**Comment by willstenzel** [comment]
> I believe once @willstenzel's login pr gets merged we will. He added `enabled` to the course model

Yep, that's correct
