### ISSUE TITLE
Allow a TA to start helping a student while they are drafting their question

### ISSUE THREAD

**Issue by mister-walter** [sandboxnu/office-hours#543]
It may be faster for a student to directly ask their question to the TA, rather than to draft something before a TA can connect with them. On the other hand, I can see why it might be desirable to force a student to type out a question before getting help from a TA.

**Comment by liustanley** [comment]
Thanks for the suggestion! We're going to add this to our roadmap 😄

**Comment by willstenzel** [comment]
@mister-walter, thanks for submitting at ticket. You're right it probably doesn't make sense to prevent a TA from helping a student even if they are still drafting. I'll make a PR for that.
