### ISSUE TITLE
Create designs for In Production page

### ISSUE THREAD

**Issue by liustanley** [sandboxnu/office-hours#558]
**Goal: 4/8**

https://www.figma.com/file/w1mo5CKKQtIA1IMvetBzOh/%F0%9F%96%A5-In-Production

**Comment by alekopel** [comment]
I believe Figma link was not shared properly so I hope you don't mind I created a new one. 
https://www.figma.com/file/LwRBdKHvzLFFTqoTWtWLap/In-Production-Sceens-Office-Hours?node-id=0%3A1
