### ISSUE TITLE
Correctly parse when an instance of a recurring event is changed

### ISSUE THREAD

**Issue by liustanley** [sandboxnu/office-hours#574]
Ex: I have a recurring event from 2-4pm on my calendar, but I change this week's event to 3-5pm. This is ignored in our parser

**Comment by dfarooq610** [comment]
The calendar parser gives us VEVENTs. This will have an RRULE if it's recurring, EXDates for exclusionary days in the recurrence (a cancelled event), and a field called RECURRENCES if there is an edited one off event (shifted back an hour). We currently handle EXDates but not the Recurrences. 

Modify the addDatesToRRule method to account for the events in the RECURRENCES field. Ensure correctness by writing new tests for this. Reach out to Danish if you have any questions!

**Comment by dfarooq610** [comment]
Closing for now -- we plan to remove the calendar scraper altogether
