### ISSUE TITLE
Student should not be able to see the helping name on the TA Status card

### ISSUE THREAD

**Issue by willstenzel** [sandboxnu/office-hours#604]
![image](https://user-images.githubusercontent.com/33739155/108882249-2e948780-75d2-11eb-8d46-834a35b41a2f.png)

**Comment by isa3bel** [comment]
should it only show the first name?

**Comment by willstenzel** [comment]
I blocked out the users last name for privacy, that might have been slightly confusing. 

It should say "Helping a student for X min"
https://github.com/sandboxnu/office-hours/blob/7ea924037104a3d5400cd43fa277c72cda6a8945/packages/app/components/Queue/TAStatuses.tsx#L127-L127
