### ISSUE TITLE
[Queue Refactor] - Rename the Queue Model as a Session Model

### ISSUE THREAD

**Issue by dfarooq610** [sandboxnu/office-hours#716]
Rename the queue entity and some types in common if you would like.
Migration will be needed for renamed db. 

QueueModel -> SessionModel

all queues are sessions now 😱 

I have approached semantic satiation of the word queue.

**Comment by willstenzel** [comment]
@dfarooq610 is the session model going to be a new table in the db or a rename of the queue model?
