### ISSUE TITLE
[Queue Refactor] Prevent TAs from checking into Prof queues

### ISSUE THREAD

**Issue by IrisLiu-00** [sandboxnu/office-hours#774]
Depends on https://github.com/sandboxnu/office-hours/pull/757 getting merged first

If you log in as a TA and enter a professor queue name (eg "Professor Li's Hours") to the custom queue creation it will let you check in to it 😰 but you get into a really weird state of data where you can't check out again.

Honestly I thought we should have had backend validation preventing TAs from checking into professor queues, but evidently there's something weird here.

- Investigate what the problem is - you'll probably end up having to add that backend validation 
- If TA tries to check into a Prof queue, return some error from the endpoint with an error message

**Comment by VKong6019** [comment]
Oh actually i will unassign, this seems like it's fixed in the referenced pr

https://github.com/sandboxnu/office-hours/pull/757#discussion_r755639369
