### ISSUE TITLE
No courses screen flashes when logging in

### ISSUE THREAD

**Issue by dfarooq610** [sandboxnu/office-hours#828]
When someone logs in, we flash the no courses page while we fetch their course info. Add a loading state when launching the app and await the initial profile request

**Comment by IrisLiu-00** [comment]
Reopening because it looks like this is still not fixed on staging 🤔

**Comment by ashdawngary** [comment]
https://github.com/sandboxnu/office-hours/commit/3d1ab139cd19dd7c58b3a45f1f6b283f4b0fd86a accidentally undid the past changes :sadcat:
