### ISSUE TITLE
Reach out to all the TAs you know

### ISSUE THREAD

**Issue by liustanley** [sandboxnu/office-hours#86]
Email template: https://www.notion.so/TA-Email-Template-cff946b0712f4253ae5467c3c0b877d1

Requirements:
- Has TA'ed online
- TA'ed a Khoury class (ideally Fundies or OOD)

### Invited
- Julia Abouelheiga - Fundies 2 Summer 1

### Friday 24th @ 7pm
- Iris Liu - Fundies 1 Spring + Summer 1
- Ifteda Ahmed-Syed - Fundies 2 Spring + Summer 1
- Stanley Wu - Fundies 1 Spring + Summer 1
- Danish Farooq - OOD Summer 1

### Tuesday 28th @ 8pm
- Sidney LaFontaine - Fundies 1 Spring + Summer 1 (confirm w him that 8pm is ok)
- Yuval Timen - Fundies 2 Spring
- Isabel Tripp - Fundies 1
- Iman Moreira - Fundies 1 Spring + Summer 1
- Cassie Harbour

### Async (Send questions and receive text responses)
- Tatiana Ediger - Fundies 1 Spring + Summer 1
- Pablo Kvitca - Fundies 2 Spring + Summer 1
- Varun Tankala - Fundies 2 Spring + Summer 1
- Angela Hu - Fundies 2 Spring + Summer 1

### Stanley interviewing
- Ameya Bhat - Fundies 2 Spring + Summer 1

**Comment by willstenzel** [comment]
Is there any cap to the number of TA's we might want for each of the time slots?

**Comment by liustanley** [comment]
Not sure, no more than 10-15 TA's as a ballpark estimate? We can keep track of attendees in this issue
