### ISSUE TITLE
Keyboard Shortcuts

### ISSUE THREAD

**Issue by IrisLiu-00** [sandboxnu/office-hours#863]
Investigate and implement keyboard shortcuts for the app.

Proposed keybindings (feel free to add more)
- N - new question
- E - edit question
- <Enter> from question form - submit question
- H - help student
- D - delete student question
- arrows to navigate between student questions

Considerations
- we probably only want keybindings to work while youre on the specific page
- idk if there will be permissions issues (eg. students that accidentally hit a TA keybinding should not trigger the TA aciton)
- look into React Hotkeys lib

**Comment by VKong6019** [comment]
im just dumping my research here:
- https://www.npmjs.com/package/react-hot-keys
- https://www.npmjs.com/package/react-hotkeys-hook (this is just the hooks version of the above package)
- https://www.npmjs.com/package/mousetrap (apparently this one isn't active)

https://www.npmtrends.com/hotkeys-js-vs-keymaster-vs-mousetrap-vs-react-hot-keys (very cool graph)
