### ISSUE TITLE
Change "Disable Queue" wording to "Delete Queue"

### ISSUE THREAD

**Issue by IrisLiu-00** [sandboxnu/office-hours#875]
from a user's perspective, once a queue is disabled it never appears again. So we should change the wording on the Queue page button to say "Delete queue" (this might also require changes to the popup when you click the button)

**Comment by dfarooq610** [comment]
Done via https://github.com/sandboxnu/office-hours/commit/9716de1ff7edd1c438c8566197ba2b60b92d32f5
