### ISSUE TITLE
Research Dynamic Tab Title + Favicon when new students enter the queue

### ISSUE THREAD

**Issue by dfarooq610** [sandboxnu/office-hours#901]
It would be cool to have a feature like Outlook or Slack that indicates that new students are in the queue via the tab title. We can design a new favicon, but ideally the tab text could read something like (1) | Online Queue | Khoury Office Hours if a new student has joined the queue since the last time the TA has viewed the tab. 

Spend some time to research how something like this would be implemented, and report if it would be feasible

![image](https://user-images.githubusercontent.com/59672089/171186708-1731ee4c-85d8-4044-9295-889fa03515bf.png)

**Comment by VKong6019** [comment]
Dumping some research here:

https://stackoverflow.com/questions/49902883/check-if-the-browser-tab-is-in-focus-in-reactjs

http://lab.ejci.net/favico.js/
